### ISSUE TITLE
Removal of commits from 283 to 286

### ISSUE THREAD

**Issue by aniketp** [SummerCamp17/Gymkhana-Nominations#11]
Angular boilerplate was causing a lot of problem in tracking the changes that were being done in actual code due to large number of files. 
So I removed it till the time its absolutely necessary to include it.

**Comment by aniketp** [comment]
@aasis21 Please redo the changes that you did in these commits. Sorry for the trouble

**Comment by aniketp41** [comment]
@aasis21 Please redo the changes that you did in these commits. Sorry for the trouble.

**Comment by aasis21** [comment]
I would suggest to revert the repository to 278th commit, We would add angular components later after having a little more comfortable with it. Furthermore we haven't taken backup of project up to that point.

**Comment by aniketp** [comment]
I have updated gitignore file so the template will not cause any more problem.

**Comment by aniketp** [comment]
We'll do the rest of the work in angular-CLI as @yashsriv suggested. So no need of the current template. 
Hence removing it.
