### ISSUE TITLE
Nomination forms are automatically created

### ISSUE THREAD

**Issue by aniketp** [SummerCamp17/Gymkhana-Nominations#7]
When you add a question in the nominations form, It automatically creates a form and sends for application to the junta. So when you are adding questions, users can see the edition .

Please change it so that once the creator hits submit button , only then can a form be submmited

**Comment by aasis21** [comment]
This thing is not worked till now, When nomination approval comes in effect this bug will automatically excluded.

**Comment by aasis21** [comment]
bug fixed
